In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("input.csv")
query_df = pd.read_csv("query.csv")

In [13]:
ls = []
sumls = []
for idx, row in query_df.iterrows():

        diffs = (df[["x", "y"]] - row).pow(2)
        sum = diffs.sum(axis=1)
        ls.append(diffs)
        sumls.append(sum)

In [14]:
ls

[                x            y
 0     2820.398011  2491.384063
 1      980.861967   468.729176
 2       55.336744    59.071538
 3      365.313820   728.076580
 4     6925.823712   883.749653
 ...           ...          ...
 9995  2654.462600  2014.595399
 9996    60.168083   473.799886
 9997   130.074986    90.430923
 9998    30.232529  2223.635211
 9999  2498.232791   174.687293

 [10000 rows x 2 columns],
                 x            y
 0       37.494602  6715.163242
 1      779.079031  2881.809468
 2     2682.394280  1577.530200
 3     1609.415306    25.496836
 4      575.559962  3814.329777
 ...           ...          ...
 9995    59.432167  5916.159938
 9996  4487.326762   105.378202
 9997  4989.408511   507.277233
 9998  2887.159170  6270.702927
 9999    85.532502   354.019325

 [10000 rows x 2 columns],
                 x            y
 0      141.043482  5525.988116
 1       98.258266  2122.756174
 2     1141.924918  1030.989487
 3      489.208677     6.551912
 4     1763.184223  2932.347167
 ...           ...          ...
 9995   105.888841  4803.525176
 9996  2399.829585     7.055819
 9997  2770.578901   222.418640
 9998  1276.835514  5123.504664
 9999    76.581368   125.580978

 [10000 rows x 2 columns],
                 x            y
 0     3960.557270    14.314728
 1     1692.849712  1027.016172
 2      298.059718  2117.053179
 3      837.449714  6509.285223
 4     8657.757780   574.528305
 ...           ...          ...
 9995  3763.456379    77.669018
 9996     4.279644  5694.844279
 9997     2.494830  3995.095109
 9998   234.823457    42.795285
 9999  3576.980569  4477.507391

 [10000 rows x 2 columns],
                 x            y
 0     1349.161307  4253.424674
 1      223.270165  1365.647837
 2       79.881073   528.554795
 3        7.489506   136.384458
 4     4468.260122  2027.921166
 ...           ...          ...
 9995  1235.170233  3622.687190
 9996   582.416033    41.762953
 9997   771.813435    33.582037
 9998   118.332557  3901.246011
 9999  1129.352243     4.358017

 [10000 rows x 2 columns],
                 x            y
 0     4525.309485   371.509998
 1     2068.586577    80.802435
 2      466.640707   526.857221
 3     1107.304520  3320.302473
 4     9483.747652     0.830367
 ...           ...          ...
 9995  4314.450664   202.922099
 9996    41.039298  2746.401040
 9997     7.606337  1611.917240
 9998   386.571141   272.787012
 9999  4114.622824  1923.357832

 [10000 rows x 2 columns],
                 x            y
 0     2319.402731   302.253098
 1      695.454653   118.334894
 2        6.208197   617.151668
 3      200.673934  3541.586822
 4     6126.864826     7.842304
 ...           ...          ...
 9995  2169.159401   152.668411
 9996   161.392900  2947.977791
 9997   267.397187  1767.181340
 9998     0.303788   213.952002
 9999  2028.158709  2092.629781

 [10000 rows x 2 columns],
                 x            y
 0      880.745839  7572.468670
 1     2648.755953  3452.305201
 2     5677.006884  2006.320342
 3     4054.072328   102.480638
 4        0.190752  4466.796052
 ...           ...          ...
 9995   977.394232  6722.427459
 9996  8197.779663   235.291717
 9997  8871.722961   761.575026
 9998  5973.183064  7100.017748
 9999  1076.001196   570.695514

 [10000 rows x 2 columns],
                 x            y
 0     1593.610914   545.269175
 1      328.745958    24.133763
 2       33.045205   356.339837
 3       35.115360  2867.137816
 4     4904.785097    10.018240
 ...           ...          ...
 9995  1469.504301   335.676542
 9996   438.658335  2335.761026
 9997   604.786391  1301.209697
 9998    59.119976   424.058053
 9999  1353.869212  1582.424444

 [10000 rows x 2 columns],
                 x            y
 0     3371.448974  3889.020413
 1     1315.910171  1162.700807
 2      153.651577   405.379799
 3      579.362237   211.256036
 4     7775.411564  1778.829473
 ...           ...          ...
 9995  3189.791290  3287.014312
 9996     7.840272    86.838171
 9997    41.580339     8.636118
 9998   109.310615  3552.598839
 9999  3018.303063     0.590880

 [10000 rows x 2 columns],
                 x            y
 0       62.351233  8433.235852
 1      192.999443  4041.022753
 2     1426.744589  2460.624886
 3      681.103276   223.083823
 4     1444.790059  5133.265702
 ...           ...          ...
 9995    39.820356  7534.783293
 9996  2805.603589   406.100697
 9997  3205.392063  1050.367105
 9998  1577.100797  7934.234801
 9999    22.764206   823.802106

 [10000 rows x 2 columns],
                 x            y
 0     1295.517978  4472.327307
 1      201.770690  1490.874891
 2       93.610420   607.499057
 3        3.996279   100.424436
 4     4370.190851  2179.920808
 ...           ...          ...
 9995  1183.866571  3824.920214
 9996   618.562848    23.090427
 9997   813.342319    55.534948
 9998   134.924567  4111.006567
 9999  1080.319220    14.023249

 [10000 rows x 2 columns],
                 x            y
 0     2744.744252  1391.465587
 1      936.458120    81.698849
 2       45.181982    24.261649
 3      338.415456  1567.709134
 4     6806.979524   292.975070
 ...           ...          ...
 9995  2581.083440  1041.535673
 9996    71.807346  1181.871459
 9997   146.946638   489.335550
 9998    22.860818  1193.289600
 9999  2427.061122   667.103389

 [10000 rows x 2 columns],
                 x            y
 0       19.025518  4814.590247
 1      303.696098  1691.153469
 2     1706.245730   737.626666
 3      878.079727    56.391269
 4     1188.590399  2420.778681
 ...           ...          ...
 9995     7.705524  4141.916976
 9996  3192.521586     5.259971
 9997  3618.099090    99.280592
 9998  1870.318843  4439.412833
 9999     1.529502    39.144419

 [10000 rows x 2 columns],
                 x            y
 0      170.704675  3218.307121
 1       76.096028   810.342377
 2     1062.965555   210.312648
 3      438.016143   406.689140
 4     1864.470455  1335.484856
 ...           ...          ...
 9995   131.777943  2672.952404
 9996  2284.728004   223.520014
 9997  2646.800166     7.253102
 9998  1193.260866  2912.954740
 9999    98.809666    40.967335

 [10000 rows x 2 columns],
                 x            y
 0     3938.850313  3420.215944
 1     1678.668483   913.187976
 2      292.126489   264.213553
 3      827.484224   339.077170
 4     8625.649535  1466.642838
 ...           ...          ...
 9995  3742.297201  2857.232883
 9996     3.594938   174.189811
 9997     3.070209     0.884863
 9998   229.560453  3105.195690
 9999  3556.353007    21.604704

 [10000 rows x 2 columns],
                 x            y
 0       28.486717  3202.437621
 1      270.648849   802.389019
 2     1626.610335   206.270460
 3      821.220221   412.357043
 4     1256.802421  1325.269055
 ...           ...          ...
 9995    14.072645  2658.491584
 9996  3083.240342   227.727021
 9997  3501.700363     8.027020
 9998  1786.897736  2897.857800
 9999     4.893829    42.779634

 [10000 rows x 2 columns],
                 x            y
 0        1.564276   639.788032
 1      421.809168     8.818409
 2     1972.944697   286.758110
 3     1072.138414  2662.831314
 4      983.752231    26.093630
 ...           ...          ...
 9995     0.112381   410.650354
 9996  3553.771534  2151.724037
 9997  4002.049183  1164.805859
 9998  2149.091770   507.857864
 9999     3.513317  1431.613354

 [10000 rows x 2 columns],
                 x            y
 0      425.858514  2430.637714
 1        1.327943   442.592648
 2      626.611677    50.034867
 3      178.433371   761.492987
 4     2575.608586   847.721598
 ...           ...          ...
 9995   362.917633  1960.007882
 9996  1618.283032   500.829173
 9997  1925.114084   102.450546
 9998   727.524842  2166.266537
 9999   306.643698   191.246779

 [10000 rows x 2 columns],
                 x            y
 0       13.907213   544.647193
 1      651.165327    24.264831
 2     2440.141665   356.842968
 3     1423.060396  2868.564654
 4      696.161721     9.934085
 ...           ...          ...
 9995    28.251140   335.188566
 9996  4172.315854  2337.048891
 9997  4656.929527  1302.170978
 9998  2635.615475   423.509563
 9999    46.981873  1583.484504

 [10000 rows x 2 columns],
                 x            y
 0     3597.101920   973.598579
 1     1458.257726     8.637305
 2      204.698605   121.559974
 3      675.044025  2087.952535
 4     8116.200688   121.367725
 ...           ...          ...
 9995  3409.380655   685.026944
 9996     0.789226  1638.482234
 9997    20.580896   796.410311
 9998   152.938642   809.073177
 9999  3232.007742  1019.407216

 [10000 rows x 2 columns],
                 x            y
 0     1411.843111   137.410694
 1      249.191393   273.617296
 2       65.513672   930.599835
 3       12.818303  4247.706290
 4     4581.748629    71.632666
 ...           ...          ...
 9995  1295.176332    44.792353
 9996   542.411411  3595.019361
 9997   725.653736  2275.390460
 9998   100.691336    80.351525
 9999  1186.761577  2642.830539

 [10000 rows x 2 columns],
                 x            y
 0     4675.607322  2097.370007
 1     2170.600991   307.421529
 2      515.737753    12.738383
 3     1182.271669   967.185624
 4     9700.777892   655.934245
 ...           ...          ...
 9995  4461.234078  1661.991548
 9996    56.462966   669.963787
 9997    14.945577   185.674182
 9998   431.368168  1852.331663
 9999  4257.995501   300.455282

 [10000 rows x 2 columns],
                 x            y
 0       23.723114    55.840564
 1      710.720490   432.263919
 2     2554.209760  1207.931627
 3     1510.478353  4819.692615
 4      637.233106   161.625064
 ...           ...          ...
 9995    41.687430     5.968897
 9996  4321.072646  4122.674536
 9997  4814.014507  2698.867889
 9998  2754.113243    22.224859
 9999    63.931741  3097.817850

 [10000 rows x 2 columns],
                 x            y
 0     4588.639068  5349.558696
 1     2111.475150  2013.950995
 2      487.126468   955.595777
 3     1138.742509    14.107409
 4     9575.328706  2804.214902
 ...           ...          ...
 9995  4376.292400  4639.129519
 9996    47.269279     2.131502
 9997    10.413739   188.166889
 9998   405.236469  4953.674894
 9999  4175.020609   100.199682

 [10000 rows x 2 columns],
                 x            y
 0       11.817089  2191.762371
 1      636.366358   344.200812
 2     2411.414137    21.052466
 3     1401.142225   904.830384
 4      711.636458   709.179414
 ...           ...          ...
 9995    25.235972  1746.131639
 9996  4134.725042   618.240836
 9997  4617.210785   158.937003
 9998  2605.756124  1941.101396
 9999    43.068953   266.160839

 [10000 rows x 2 columns],
                 x            y
 0      156.192165  7866.854918
 1     1175.556541  3651.988003
 2     3383.311341  2159.212509
 3     2161.498765   139.207718
 4      310.338535  4693.545209
 ...           ...          ...
 9995   198.348602  6999.961188
 9996  5381.970541   289.495983
 9997  5930.562908   856.850497
 9998  3612.814722  7385.161607
 9999   244.071291   653.548477

 [10000 rows x 2 columns],
                 x            y
 0      285.173584   915.683842
 1     1495.816499     3.986636
 2     3913.207571   143.225768
 3     2588.908568  2174.953069
 4      174.954350   101.494125
 ...           ...          ...
 9995   341.252683   636.590571
 9996  6045.266479  1715.653073
 9997  6625.885933   850.481468
 9998  4159.745813   756.356639
 9999   400.487273  1080.465166

 [10000 rows x 2 columns],
                 x            y
 0       34.826239     7.441511
 1      252.407178   960.474644
 2     1581.428319  2021.031011
 3      789.208730  6340.072746
 4     1297.115552   525.040049
 ...           ...          ...
 9995    18.622967    60.177799
 9996  3020.915138  5536.643377
 9997  3435.259360  3862.771296
 9998  1739.526571    30.098860
 9999     7.707738  4337.356723

 [10000 rows x 2 columns],
                 x            y
 0      650.776457  2228.813907
 1     2237.197693   358.977578
 2     5066.431968    24.823816
 3     3540.792149   881.279067
 4       21.194917   730.322334
 ...           ...          ...
 9995   734.207473  1779.219371
 9996  7460.562714   598.800250
 9997  8104.101331   149.156590
 9998  5346.436229  1975.979071
 9999   819.987013   253.458584

 [10000 rows x 2 columns],
                 x            y
 0      534.124477  4968.652288
 1        1.748820  1782.955330
 2      508.837164   798.667311
 3      118.441907    41.062370
 4     2832.926979  2530.374574
 ...           ...          ...
 9995   463.333835  4284.899791
 9996  1425.296198     1.420967
 9997  1714.070002   122.442723
 9998   600.145875  4587.398718
 9999   399.441732    54.139715

 [10000 rows x 2 columns],
                 x            y
 0      355.253063  7039.421523
 1        8.646808  3095.547929
 2      719.333553  1736.663545
 3      229.403649    49.064422
 4     2397.304127  4059.654930
 ...           ...          ...
 9995   297.984088  6220.751170
 9996  1765.350163   149.341830
 9997  2085.228622   599.171347
 9998   827.186493  6584.175252
 9999   247.214721   431.416255

 [10000 rows x 2 columns],
                 x            y
 0      321.580160  6240.098522
 1     1577.786430  2573.602112
 2     4045.113746  1351.762950
 3     2696.402044     4.400067
 4      148.387923  3458.434394
 ...           ...          ...
 9995   380.975696  5470.787557
 9996  6208.949028    53.488499
 9997  6797.197470   383.024450
 9998  4295.709763  5811.922311
 9999   443.428877   251.653675

 [10000 rows x 2 columns],
                 x            y
 0      215.820487     1.739761
 1       50.379810   726.012117
 2      959.619286  1673.543430
 3      372.621447  5711.982754
 4     2007.483045   355.957616
 ...           ...          ...
 9995   171.738078    13.767972
 9996  2131.982716  4950.770375
 9997  2482.194980  3376.107786
 9998  1083.606446     2.071669
 9999   133.766232  3820.686043

 [10000 rows x 2 columns],
                 x            y
 0      193.219675   442.017557
 1       62.226154    52.408891
 2     1009.218812   449.599083
 3      403.764298  3121.730322
 4     1937.272902     0.702872
 ...           ...          ...
 9995   151.644584   255.830164
 9996  2205.606059  2566.080737
 9997  2561.586049  1474.488592
 9998  1136.273763   333.642519
 9999   116.106083  1772.956058

 [10000 rows x 2 columns],
                 x            y
 0       47.173063   490.934943
 1      222.619492    37.290079
 2     1505.462314   402.841566
 3      735.818260  2996.424761
 4     1367.696378     3.885679
 ...           ...          ...
 9995    27.902930   293.352282
 9996  2915.564074  2452.592830
 9997  3322.853423  1388.772048
 9998  1659.808156   376.310424
 9999    14.011323  1678.839712

 [10000 rows x 2 columns],
                 x            y
 0     2624.554270  1399.609830
 1      866.813707    83.681285
 2       30.934190    23.199689
 3      297.085510  1559.088983
 4     6616.930635   296.718557
 ...           ...          ...
 9995  2464.572537  1048.583420
 9996    92.810577  1174.388447
 9997   176.413062   484.524805
 9998    13.114507  1200.832494
 9999  2314.120755   661.484383

 [10000 rows x 2 columns],
                 x            y
 0     2065.007288  6996.850925
 1      559.495047  3067.339730
 2        0.051167  1715.551454
 3      131.059364    45.569530
 4     5708.779503  4027.341941
 ...           ...          ...
 9995  1923.384592  6180.736367
 9996   237.834294   143.196408
 9997   363.669111   586.797207
 9998     4.694402  6543.006323
 9999  1790.750198   420.926070

 [10000 rows x 2 columns],
                 x            y
 0     2961.997255    29.568927
 1     1065.077848   521.020811
 2       76.661961  1353.521276
 3      417.384858  5106.378491
 4     7146.732363   217.506670
 ...           ...          ...
 9995  2791.885060     0.166635
 9996    41.473527  4388.132305
 9997   101.772336  2914.439825
 9998    46.447305     7.179196
 9999  2631.601695  3328.478389

 [10000 rows x 2 columns],
                 x            y
 0      293.395866  7684.568088
 1     1514.572262  3528.129082
 2     3943.507754  2064.221375
 3     2613.564946   115.885393
 4      168.618332  4552.987524
 ...           ...          ...
 9995   350.241669  6828.071629
 9996  6082.912826   255.390994
 9997  6665.295974   797.406360
 9998  4190.984086  7208.576929
 9999   410.220344   601.768487

 [10000 rows x 2 columns],
                 x            y
 0     4597.899584  1460.142978
 1     2117.758482    98.966786
 2      490.146884    16.129444
 3     1143.358091  1496.517095
 4     9588.703981   324.935888
 ...           ...          ...
 9995  4385.336215  1101.064730
 9996    48.213375  1120.166853
 9997    10.859344   449.926312
 9998   407.991744  1256.949790
 9999  4183.854115   620.950634

 [10000 rows x 2 columns],
                 x            y
 0     1184.004178  1927.449594
 1      159.281012   244.581971
 2      126.769374     2.804833
 3        0.172330  1088.599529
 4     4163.278978   562.490855
 ...           ...          ...
 9995  1077.376855  1511.126219
 9996   699.859967   771.616300
 9997   906.196624   240.887628
 9998   174.230663  1692.861588
 9999   978.705363   369.714813

 [10000 rows x 2 columns],
                 x            y
 0      839.943913  2934.209766
 1     2577.642605   671.055267
 2     5572.673013   142.572706
 3     3965.979219   516.576255
 4        1.282168  1154.810811
 ...           ...          ...
 9995   934.386017  2414.624094
 9996  8072.306281   306.682911
 9997  8741.174329    27.614365
 9998  5866.149722  2642.989846
 9999  1030.851785    80.323750

 [10000 rows x 2 columns],
                 x            y
 0     1437.573326  3673.250582
 1      260.068536  1046.117227
 2       60.112238   337.801697
 3       15.375097   265.341714
 4     4628.007237  1633.898348
 ...           ...          ...
 9995  1319.825430  3088.894717
 9996   526.651285   122.619379
 9997   707.406658     1.402007
 9998    93.967120  3346.508888
 9999  1210.361456     6.367299

 [10000 rows x 2 columns],
                 x            y
 0      454.215505  4214.292052
 1     1857.699292  1343.513285
 2     4486.438911   514.818570
 3     3058.816390   143.498395
 4       77.471369  2000.928546
 ...           ...          ...
 9995   524.330984  3586.579382
 9996  6752.987115    45.739957
 9997  7365.895250    30.187279
 9998  4750.151151  3863.772281
 9999   597.187838     3.192942

 [10000 rows x 2 columns],
                 x            y
 0     3725.669007  7821.640619
 1     1540.527562  3621.202439
 2      236.227866  2135.555827
 3      731.379204   133.249603
 4     8308.755093  4658.635895
 ...           ...          ...
 9995  3534.577887  6957.314489
 9996     0.030286   280.875096
 9997    12.070087   841.972123
 9998   180.344768  7341.355450
 9999  3353.934540   640.562760

 [10000 rows x 2 columns],
                 x            y
 0      186.010391   482.182572
 1       66.424798    39.752472
 2     1025.920248   410.844897
 3      414.353402  3018.184340
 4     1914.296747     3.142880
 ...           ...          ...
 9995   145.265653   286.595583
 9996  2230.263507  2472.282764
 9997  2588.153605  1403.598337
 9998  1153.991165   368.652534
 9999   110.533007  1695.137073

 [10000 rows x 2 columns],
                 x            y
 0     4324.106763   196.769190
 1     1933.293808   202.668476
 2      403.583520   795.269387
 3     1008.932993  3952.538358
 4     9191.450945    37.925828
 ...           ...          ...
 9995  4118.045355    80.962607
 9996    23.948420  3323.899183
 9997     1.551218  2060.782253
 9998   329.383754   126.992944
 9999  3922.873389  2411.129568

 [10000 rows x 2 columns],
                 x            y
 0     4512.720754  1211.361532
 1     2060.078141    42.784777
 2      462.604167    55.106063
 3     1101.081772  1771.739921
 4     9465.519556   213.708737
 ...           ...          ...

In [15]:
sumls

[0       5311.782074
 1       1449.591143
 2        114.408282
 3       1093.390400
 4       7809.573364
            ...
 9995    4669.057999
 9996     533.967969
 9997     220.505910
 9998    2253.867740
 9999    2672.920084
 Length: 10000, dtype: float64,
 0       6752.657844
 1       3660.888499
 2       4259.924480
 3       1634.912142
 4       4389.889740
            ...
 9995    5975.592105
 9996    4592.704964
 9997    5496.685744
 9998    9157.862097
 9999     439.551828
 Length: 10000, dtype: float64,
 0       5667.031598
 1       2221.014441
 2       2172.914406
 3        495.760589
 4       4695.531391
            ...
 9995    4909.414018
 9996    2406.885404
 9997    2992.997541
 9998    6400.340178
 9999     202.162346
 Length: 10000, dtype: float64,
 0       3974.871998
 1       2719.865884
 2       2415.112897
 3       7346.734937
 4       9232.286085
            ...
 9995    3841.125398
 9996    5699.123923
 9997    3997.589940
 9998     277.618742
 9999    8054.487959
 Length: 10000, dtype: float64,
 0       5602.585982
 1       1588.918002
 2        608.435869
 3        143.873964
 4       6496.181288
            ...
 9995    4857.857424
 9996     624.178986
 9997     805.395472
 9998    4019.578568
 9999    1133.710261
 Length: 10000, dtype: float64,
 0       4896.819483
 1       2149.389012
 2        993.497928
 3       4427.606993
 4       9484.578019
            ...
 9995    4517.372763
 9996    2787.440338
 9997    1619.523578
 9998     659.358153
 9999    6037.980656
 Length: 10000, dtype: float64,
 0       2621.655828
 1        813.789547
 2        623.359865
 3       3742.260756
 4       6134.707130
            ...
 9995    2321.827812
 9996    3109.370691
 9997    2034.578527
 9998     214.255790
 9999    4120.788490
 Length: 10000, dtype: float64,
 0        8453.214509
 1        6101.061154
 2        7683.327226
 3        4156.552967
 4        4466.986805
             ...
 9995     7699.821691
 9996     8433.071380
 9997     9633.297988
 9998    13073.200812
 9999     1646.696710
 Length: 10000, dtype: float64,
 0       2138.880088
 1        352.879721
 2        389.385042
 3       2902.253176
 4       4914.803337
            ...
 9995    1805.180843
 9996    2774.419360
 9997    1905.996089
 9998     483.178029
 9999    2936.293655
 Length: 10000, dtype: float64,
 0       7260.469387
 1       2478.610978
 2        559.031376
 3        790.618274
 4       9554.241037
            ...
 9995    6476.805602
 9996      94.678444
 9997      50.216457
 9998    3661.909454
 9999    3018.893943
 Length: 10000, dtype: float64,
 0       8495.587085
 1       4234.022195
 2       3887.369474
 3        904.187099
 4       6578.055761
            ...
 9995    7574.603649
 9996    3211.704286
 9997    4255.759169
 9998    9511.335598
 9999     846.566312
 Length: 10000, dtype: float64,
 0       5767.845285
 1       1692.645580
 2        701.109477
 3        104.420715
 4       6550.111659
            ...
 9995    5008.786784
 9996     641.653275
 9997     868.877267
 9998    4245.931134
 9999    1094.342469
 Length: 10000, dtype: float64,
 0       4136.209839
 1       1018.156969
 2         69.443632
 3       1906.124590
 4       7099.954594
            ...
 9995    3622.619113
 9996    1253.678805
 9997     636.282188
 9998    1216.150418
 9999    3094.164511
 Length: 10000, dtype: float64,
 0       4833.615765
 1       1994.849566
 2       2443.872396
 3        934.470996
 4       3609.369080
            ...
 9995    4149.622500
 9996    3197.781557
 9997    3717.379682
 9998    6309.731676
 9999      40.673921
 Length: 10000, dtype: float64,
 0       3389.011796
 1        886.438405
 2       1273.278204
 3        844.705282
 4       3199.955311
            ...
 9995    2804.730347
 9996    2508.248018
 9997    2654.053268
 9998    4106.215607
 9999     139.777001
 Length: 10000, dtype: float64,
 0        7359.066257
 1        2591.856458
 2         556.340041
 3        1166.561394
 4       10092.292373
             ...
 9995     6599.530085
 9996      177.784749
 9997        3.955071
 9998     3334.756143
 9999     3577.957711
 Length: 10000, dtype: float64,
 0       3230.924338
 1       1073.037868
 2       1832.880794
 3       1233.577265
 4       2582.071476
            ...
 9995    2672.564230
 9996    3310.967364
 9997    3509.727384
 9998    4684.755536
 9999      47.673464
 Length: 10000, dtype: float64,
 0        641.352308
 1        430.627577
 2       2259.702806
 3       3734.969727
 4       1009.845861
            ...
 9995     410.762734
 9996    5705.495571
 9997    5166.855041
 9998    2656.949634
 9999    1435.126671
 Length: 10000, dtype: float64,
 0       2856.496228
 1        443.920591
 2        676.646544
 3        939.926358
 4       3423.330184
            ...
 9995    2322.925515
 9996    2119.112205
 9997    2027.564630
 9998    2893.791380
 9999     497.890477
 Length: 10000, dtype: float64,
 0        558.554406
 1        675.430158
 2       2796.984634
 3       4291.625049
 4        706.095807
            ...
 9995     363.439705
 9996    6509.364745
 9997    5959.100505
 9998    3059.125038
 9999    1630.466377
 Length: 10000, dtype: float64,
 0       4570.700498
 1       1466.895030
 2        326.258579
 3       2762.996560
 4       8237.568413
            ...
 9995    4094.407599
 9996    1639.271460
 9997     816.991206
 9998     962.011819
 9999    4251.414959
 Length: 10000, dtype: float64,
 0       1549.253805
 1        522.808689
 2        996.113507
 3       4260.524593
 4       4653.381295
            ...
 9995    1339.968684
 9996    4137.430772
 9997    3001.044196
 9998     181.042861
 9999    3829.592116
 Length: 10000, dtype: float64,
 0        6772.977329
 1        2478.022520
 2         528.476136
 3        2149.457293
 4       10356.712137
             ...
 9995     6123.225626
 9996      726.426753
 9997      200.619759
 9998     2283.699830
 9999     4558.450783
 Length: 10000, dtype: float64,
 0         79.563678
 1       1142.984410
 2       3762.141387
 3       6330.170968
 4        798.858170
            ...
 9995      47.656327
 9996    8443.747181
 9997    7512.882396
 9998    2776.338102
 9999    3161.749591
 Length: 10000, dtype: float64,
 0        9938.197764
 1        4125.426145
 2        1442.722245
 3        1152.849917
 4       12379.543608
             ...
 9995     9015.421919
 9996       49.400781
 9997      198.580627
 9998     5358.911363
 9999     4275.220290
 Length: 10000, dtype: float64,
 0       2203.579460
 1        980.567171
 2       2432.466603
 3       2305.972609
 4       1420.815872
            ...
 9995    1771.367611
 9996    4752.965878
 9997    4776.147788
 9998    4546.857520
 9999     309.229792
 Length: 10000, dtype: float64,
 0        8023.047083
 1        4827.544544
 2        5542.523850
 3        2300.706483
 4        5003.883744
             ...
 9995     7198.309791
 9996     5671.466524
 9997     6787.413404
 9998    10997.976329
 9999      897.619768
 Length: 10000, dtype: float64,
 0       1200.857427
 1       1499.803135
 2       4056.433338
 3       4763.861637
 4        276.448475
            ...
 9995     977.843255
 9996    7760.919552
 9997    7476.367401
 9998    4916.102451
 9999    1480.952439
 Length: 10000, dtype: float64,
 0         42.267750
 1       1212.881821
 2       3602.459329
 3       7129.281476
 4       1822.155600
            ...
 9995      78.800766
 9996    8557.558514
 9997    7298.030655
 9998    1769.625431
 9999    4345.064461
 Length: 10000, dtype: float64,
 0       2879.590364
 1       2596.175271
 2       5091.255784
 3       4422.071217
 4        751.517251
            ...
 9995    2513.426843
 9996    8059.362964
 9997    8253.257920
 9998    7322.415300
 9999    1073.445597
 Length: 10000, dtype: float64,
 0       5502.776764
 1       1784.704150
 2       1307.504474
 3        159.504278
 4       5363.301553
            ...
 9995    4748.233626
 9996    1426.717165
 9997    1836.512725
 9998    5187.544594
 9999     453.581446
 Length: 10000, dtype: float64,
 0       7394.674587
 1       3104.194737
 2       2455.997098
 3        278.468071
 4       6456.959057
            ...
 9995    6518.735259
 9996    1914.691993
 9997    2684.399969
 9998    7411.361745
 9999     678.630976
 Length: 10000, dtype: float64,
 0        6561.678681
 1        4151.388542
 2        5396.876696
 3        2700.802112
 4        3606.822317
             ...
 9995     5851.763253
 9996     6262.437526
 9997     7180.221920
 9998    10107.632074
 9999      695.082552
 Length: 10000, dtype: float64,
 0        217.560248
 1        776.391926
 2       2633.162715
 3       6084.604201
 4       2363.440661
            ...
 9995     185.506050
 9996    7082.753091
 9997    5858.302766
 9998    1085.678116
 9999    3954.452275
 Length: 10000, dtype: float64,
 0        635.237232
 1        114.635045
 2       1458.817895
 3       3525.494620
 4       1937.975774
            ...
 9995     407.474749
 9996    4771.686796
 9997    4036.074641
 9998    1469.916283
 9999    1889.062141
 Length: 10000, dtype: float64,
 0        538.108006
 1        259.909571
 2       1908.303880
 3       3732.243021
 4       1371.582057
            ...
 9995     321.255212
 9996    5368.156903
 9997    4711.625471
 9998    2036.118580
 9999    1692.851035
 Length: 10000, dtype: float64,
 0       4024.164100
 1        950.494993
 2         54.133879
 3       1856.174493
 4       6913.649192
            ...
 9995    3513.155957
 9996    1267.199024
 9997     660.937867
 9998    1213.947001
 9999    2975.605137
 Length: 10000, dtype: float64,
 0       9061.858213
 1       3626.834777
 2       1715.602621
 3        176.628894
 4       9736.121444
            ...
 9995    8104.120960
 9996     381.030702
 9997     950.466318
 9998    6547.700725
 9999    2211.676268
 Length: 10000, dtype: float64,
 0       2991.566182
 1       1586.098659
 2       1430.183237
 3       5523.763349
 4       7364.239033
            ...
 9995    2792.051696
 9996    4429.605831
 9997    3016.212161
 9998      53.626502
 9999    5960.080084
 Length: 10000, dtype: float64,
 0        7977.963954
 1        5042.701345
 2        6007.729130
 3        2729.450339
 4        4721.605855
             ...
 9995     7178.313299
 9996     6338.303820
 9997     7462.702334
 9998    11399.561015
 9999     1011.988831
 Length: 10000, dtype: float64,
 0       6058.042562
 1       2216.725268
 2        506.276329
 3       2639.875186
 4       9913.639869
            ...
 9995    5486.400945
 9996    1168.380228
 9997     460.785656
 9998    1664.941534
 9999    4804.804749
 Length: 10000, dtype: float64,
 0       3111.453772
 1        403.862983
 2        129.574207
 3       1088.771859
 4       4725.769833
            ...
 9995    2588.503074
 9996    1471.476267
 9997    1147.084251
 9998    1867.092250
 9999    1348.420176
 Length: 10000, dtype: float64,
 0       3774.153680
 1       3248.697873
 2       5715.245719
 3       4482.555474
 4       1156.092979
            ...
 9995    3349.010111
 9996    8378.989193
 9997    8768.788694
 9998    8509.139568
 9999    1111.175535
 Length: 10000, dtype: float64,
 0       5110.823908
 1       1306.185763
 2        397.913935
 3        280.716811
 4       6261.905585
            ...
 9995    4408.720147
 9996     649.270664
 9997     708.808665
 9998    3440.476008
 9999    1216.728755
 Length: 10000, dtype: float64,
 0       4668.507557
 1       3201.212577
 2       5001.257481
 3       3202.314785
 4       2078.399915
            ...
 9995    4110.910366
 9996    6798.727071
 9997    7396.082529
 9998    8613.923432
 9999     600.380780
 Length: 10000, dtype: float64,
 0       11547.309625
 1        5161.730001
 2        2371.783692
 3         864.628808
 4       12967.390988
             ...
 9995    10491.892375
 9996      280.905382
 9997      854.042210
 9998     7521.700218
 9999     3994.497299
 Length: 10000, dtype: float64,
 0        668.192962
 1        106.177270
 2       1436.765145
 3       3432.537742
 4       1917.439626
            ...
 9995     431.861235
 9996    4702.546270
 9997    3991.751943
 9998    1522.643699
 9999    1805.670079
 Length: 10000, dtype: float64,
 0       4520.875954
 1       2135.962284
 2       1198.852907
 3       4961.471351
 4       9229.376774
            ...
 9995    4199.007962
 9996    3347.847603
 9997    2062.333471
 9998     456.376699
 9999    6334.002957
 Length: 10000, dtype: float64,
 0       5724.082287
 1       2102.862918
 2        517.710230
 3       2872.821693
 4       9679.228293
            ...
 9995    5188.715364
 9996    1399.694536
 9997     613.177266
 9998    1409.862678
 9999    4904.986066
 Length: 10000, dtype: float64,
 0         679.283433
 1        2850.298021
 2        6564.530327
 3        8887.026700
 4         281.597216
             ...
 9995      748.754775
 9996    12086.622458
 9997    11222.545072
 9998     5384.112033
 9999     4332.949387
 Length: 10000, dtype: float64]

In [ ]:
for idx, row in query_df.iterrows():

        diffs = (df[["x", "y"]] - row).pipe(lambda df: df**2).sum(axis=1)